### ISSUE TITLE
Query OR statement with multiple indices returns wrong result

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#632] opened 2018-12-13 22:29 UTC
**Test Cases:**

```Objective-C
- (void) createDocWithNumber1: (NSInteger)number1 number2: (NSInteger)number2 {
    CBLMutableDocument* doc = [[CBLMutableDocument alloc] init];
    [doc setInteger: number1 forKey: @"number1"];
    [doc setInteger: number2 forKey: @"number2"];
    [self.db saveDocument: doc error: nil];
}

- (void) testIndexMultipleValues {
    [self createDocWithNumber1: 2 number2: 4];
    [self createDocWithNumber1: 3 number2: 9];
    
    CBLQueryExpression* number1 = [CBLQueryExpression property: @"number1"];
    CBLQueryExpression* number2 = [CBLQueryExpression property: @"number2"];
    
    CBLValueIndex* index1 = [CBLIndexBuilder valueIndexWithItems: @[[CBLValueIndexItem expression: number1]]];
    Assert([self.db createIndex: index1 withName: @"Number1Index" error: nil]);
    
    CBLValueIndex* index2 = [CBLIndexBuilder valueIndexWithItems: @[[CBLValueIndexItem expression: number2]]];
    Assert([self.db createIndex: index2 withName: @"Number2Index" error: nil]);

    CBLQuery *q = [CBLQueryBuilder select: @[SEL_PROP(@"number1"),
                                             SEL_PROP(@"number2")]
                                     from: kDATA_SRC_DB
                                    where: [[number1 equalTo: EXPR_VAL(@2)] orExpression:
                                            [number2 equalTo: EXPR_VAL(@9)]]];
    
    NSString* explain = [q explain: nil];
    NSLog(@">>>> EXPLAIN: %@", explain);
    
    // Assert([explain rangeOfString: @"USING INDEX Number1Index"].location != NSNotFound);
    // Assert([explain rangeOfString: @"USING INDEX Number2Index"].location != NSNotFound);
    
    int64_t numRows = [self verifyQuery: q randomAccess: NO  test: ^(uint64_t n, CBLQueryResult *r) {
        NSLog(@">>>> ROW : %@", r.toDictionary);
    }];
    AssertEqual(numRows, 2u);
}
```

**Expected Result:** 
2 rows returned

**Actual Result:**
1 row returned which is { number1 = 3; number2 = 9; }

**Create Index Statement**

```
CREATE INDEX "Number1Index" ON "kv_default" (fl_value(body, 'number1'))
CREATE INDEX "Number2Index" ON "kv_default" (fl_value(body, 'number2'))
```

**Query Explained plan**

```
SELECT fl_result(fl_value(_doc.body, 'number1')), 
       fl_result(fl_value(_doc.body, 'number2')) 
FROM kv_default AS _doc 
WHERE (fl_value(_doc.body, 'number1') = 2 OR fl_value(_doc.body, 'number2') = 9) AND (_doc.flags & 1) = 0
3|0|0| SEARCH TABLE kv_default AS _doc USING INDEX Number2Index (<expr>=?)
```

For some reason, only one index is used and there is no table screen as well.

**Comment by pasin** [comment] 2018-12-13 22:32
If one side of the OR statement is `<=` instead of `=`, the result will be correct and two indices will be used as the query plain below.

```
SELECT fl_result(fl_value(_doc.body, 'number1')), 
       fl_result(fl_value(_doc.body, 'number2')) 
FROM kv_default AS _doc 
WHERE (fl_value(_doc.body, 'number1') <= 2 OR fl_value(_doc.body, 'number2') = 9) AND (_doc.flags & 1) = 0
4|0|0| MULTI-INDEX OR
11|4|0| SEARCH TABLE kv_default AS _doc USING INDEX Number1Index (<expr><?)
21|4|0| SEARCH TABLE kv_default AS _doc USING INDEX Number2Index (<expr>=?)
``

**Comment by pasin** [comment] 2018-12-13 23:42
JSON Query: 

```
{"WHERE":["OR",["<=",[".number1"],2],["=",[".number2"],9]],"WHAT":[[".number1"],[".number2"]]}
```

**Comment by pasin** [comment] 2018-12-13 23:51
Documents:

```
Doc1: { number1: 2, number2: 4 }
Doc2: { number1: 3, number2: 9 } 
```

**Comment by snej** [comment] 2018-12-14 00:05
I've translated the test to a LiteCore unit test, and reproduced the bug. As far as I can tell, it's a SQLite bug ... I'm going to try to write a pure-SQL version that doesn't use our `fl_value` function.

**Comment by snej** [comment] 2018-12-14 00:12
I've reduced it to plain SQL:
```
sqlite> create table docs (a int, b int);
sqlite> insert into docs (a, b) values (2, 4);
sqlite> insert into docs (a, b) values (3, 9);

sqlite> select * from docs where abs(a)=2 or abs(b)=9;
    a = 2
    b = 4

    a = 3
    b = 9
sqlite> explain query plan select * from docs where abs(a)=2 or abs(b)=9;
QUERY PLAN
`--SCAN TABLE docs

sqlite> create index ia on docs (abs(a));
sqlite> create index ib on docs (abs(b));

sqlite> select * from docs where abs(a)=2 or abs(b)=9;
    a = 3
    b = 9
sqlite> explain query plan select * from docs where abs(a)=2 or abs(b)=9;
QUERY PLAN
`--SEARCH TABLE docs USING INDEX ib (<expr>=?)
sqlite> 
```

**Comment by snej** [comment] 2018-12-14 00:47
If only one of the two indexes is created, the query behaves correctly. (But it isn't optimized.)

It looks as though SQLite _should_ be able to optimize the query with a "multi-index OR" plan making use of both indexes. I tried an equivalent situation but using regular column indexes, and the EXPLAIN QUERY PLAN looks like:
```
QUERY PLAN
`--MULTI-INDEX OR
   |--SEARCH TABLE docs USING INDEX ia2 (a=?)
   `--SEARCH TABLE docs USING INDEX ib2 (b=?)
```

**Comment by snej** [comment] 2018-12-17 17:43
It's been fixed in SQLite now:

>  https://www.sqlite.org/src/info/d96eba87698a428c1ddd0790ea04
>  https://www.sqlite.org/src/info/7e4ed8b5c2047b69

**Closed** 2019-01-15 15:34 UTC
Labels: P1: high, backlog, bug :bug:, f/query

**Comment by snej** [comment] 2019-01-24 23:50
The fix hasn't appeared in a SQLite release yet — the latest is 3.26, which was released two weeks earlier. I'm still waiting for an announcement of 3.27.
