### ISSUE TITLE
"API Connection Failure" and "API Loopback Push" tests intermittently segfault

### ISSUE THREAD

**Issue by SJLC** [couchbase/couchbase-lite-core#512] opened 2018-05-04 00:23 UTC
The "API Connection Failure" crash happens about 1 in 6 times on a 32-bit ARM target, but it does happen very rarely on 64-bit x86 (Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz with 8 cores). It was segfaulting when trying to destruct the Connection (debugging info below is for ARM)

```
(gdb) info thread
  Id   Target Id         Frame
* 1    LWP 21648         0x76eaffd0 in litecore::RefCounted::_release (this=0x3284a8)
    at /usr/src/debug/couchbase-lite-core/2.0-r0/git/vendor/BLIP-Cpp/../../LiteCore/Support/RefCounted.hh:48
  2    LWP 21473         0x76c2714c in nanosleep () from /lib/libpthread.so.0
  3    LWP 21651         0x76c22a2c in pthread_cond_wait () from /lib/libpthread.so.0
  4    LWP 21649         0x76c22a2c in pthread_cond_wait () from /lib/libpthread.so.0
  5    LWP 21477         0x76c22ec0 in pthread_cond_timedwait () from /lib/libpthread.so.0
  6    LWP 21650         0x7698f938 in write () from /lib/libc.so.6

Dump of assembler code for function litecore::blip::Connection::~Connection():
   0x76eaff4c <+0>:     push    {r4, r5, r11, lr}
   0x76eaff50 <+4>:     add     r11, sp, #8
   0x76eaff54 <+8>:     mov     r4, r0
   0x76eaff58 <+12>:    ldr     r0, [pc, #160]  ; 0x76eb0000 <litecore::blip::Connection::~Connection()+180>
   0x76eaff5c <+16>:    mov     r5, r4
   0x76eaff60 <+20>:    ldr     r1, [pc, #156]  ; 0x76eb0004 <litecore::blip::Connection::~Connection()+184>
   0x76eaff64 <+24>:    ldr     r0, [pc, r0]
   0x76eaff68 <+28>:    add     r1, pc, r1
   0x76eaff6c <+32>:    add     r2, r0, #8
   0x76eaff70 <+36>:    add     r0, r0, #28
   0x76eaff74 <+40>:    str     r2, [r4]
   0x76eaff78 <+44>:    str     r0, [r5, #8]!
   0x76eaff7c <+48>:    mov     r0, r5
   0x76eaff80 <+52>:    bl      0x76e63848 <litecore::Logging::logDebug(char const*, ...) const>
   0x76eaff84 <+56>:    mov     r0, r4
   0x76eaff88 <+60>:    ldr     r1, [r0, #72]!  ; 0x48
   0x76eaff8c <+64>:    cmp     r1, #0
   0x76eaff90 <+68>:    beq     0x76eaff98 <litecore::blip::Connection::~Connection()+76>
   0x76eaff94 <+72>:    bl      0x76cc6128 <_ZN6fleece11alloc_slice7releaseEv@plt>
   0x76eaff98 <+76>:    ldr     r0, [r4, #52]   ; 0x34
   0x76eaff9c <+80>:    cmp     r0, #0
   0x76eaffa0 <+84>:    beq     0x76eaffd8 <litecore::blip::Connection::~Connection()+140>
   0x76eaffa4 <+88>:    add     r1, r0, #4
   0x76eaffa8 <+92>:    dmb     ish
   0x76eaffac <+96>:    ldrex   r2, [r1]
   0x76eaffb0 <+100>:   sub     r2, r2, #1
   0x76eaffb4 <+104>:   strex   r3, r2, [r1]
   0x76eaffb8 <+108>:   cmp     r3, #0
   0x76eaffbc <+112>:   bne     0x76eaffac <litecore::blip::Connection::~Connection()+96>
   0x76eaffc0 <+116>:   cmp     r2, #0
   0x76eaffc4 <+120>:   dmb     ish
   0x76eaffc8 <+124>:   bgt     0x76eaffd8 <litecore::blip::Connection::~Connection()+140>
   0x76eaffcc <+128>:   ldr     r1, [r0]
=> 0x76eaffd0 <+132>:   ldr     r1, [r1, #4]

(gdb) print this
$1 = (litecore::RefCounted *) 0x3284a8
(gdb) print *this
$2 = {_vptr$RefCounted = 0x0, static kInitialRefCount = 0, _refCount = {<std::__atomic_base<int>> = {
      static _S_alignment = 4, _M_i = 0}, <No data fields>}}
```
The following are logfiles generated on the x86 with "DEBUG" defined in RefCounted.cc and RefCounted.hh since it was dying in reference counting:

[API_Connection_Failure.txt](https://github.com/couchbase/couchbase-lite-core/files/1973021/API_Connection_Failure.txt)

[API_Loopback_Push.txt](https://github.com/couchbase/couchbase-lite-core/files/1973020/API_Loopback_Push.txt)

On the x86 host, it took 8891 test runs of "API Connection Failure" to get a crash and 234 test runs of "API Loopback Push". Apparently timing on the ARM board is a lot more favorable to reproducing this bug...

**Comment by borrrden** [comment] 2018-05-04 05:41
The commit hash in the logs (12587974) does not correspond to any known commit in our code base. Have you made changes?

**Comment by SJLC** [comment] 2018-05-04 06:28
Yes, that git rev is a local commit turning on DEBUG, which was on top of 9b5a705 from master

```
commit 12587974dd74207a0f054128dcf0b783a1c0a343
Author: Ron Lockwood-Childs <rchilds@vctlabs.com>
Date:   Wed May 2 01:36:19 2018 -0700

    Enable refcounting debuggery

commit 9b5a705cd717a23cf3e27a9da20ea4523690c83a
Author: Jens Alfke <jens@couchbase.com>
Date:   Fri Apr 20 18:21:28 2018 -0700

    Fix CppTests (CMake build only)
```

This was the local commit to increase refcounting verbosity (but not anything else conditional on DEBUG):
```
commit 12587974dd74207a0f054128dcf0b783a1c0a343
Author: Ron Lockwood-Childs <rchilds@vctlabs.com>
Date:   Wed May 2 01:36:19 2018 -0700

    Enable refcounting debuggery

diff --git a/LiteCore/Support/RefCounted.cc b/LiteCore/Support/RefCounted.cc
index 592dd03..119235b 100644
--- a/LiteCore/Support/RefCounted.cc
+++ b/LiteCore/Support/RefCounted.cc
@@ -20,6 +20,7 @@
 #include "Logging.hh"
 #include <exception>
 #include <stdlib.h>
+#define DEBUG 1
 
 namespace litecore {
 
diff --git a/LiteCore/Support/RefCounted.hh b/LiteCore/Support/RefCounted.hh
index 378588b..8ca1355 100644
--- a/LiteCore/Support/RefCounted.hh
+++ b/LiteCore/Support/RefCounted.hh
@@ -18,6 +18,7 @@
 
 #pragma once
 #include <atomic>
+#define DEBUG 1
 
 namespace litecore {
 
@@ -111,3 +112,5 @@ namespace litecore {
 
 
 }
+
+#undef DEBUG
```

**Comment by snej** [comment] 2018-06-08 17:54
What's the backtrace of the crashed thread?

**Comment by SJLC** [comment] 2018-06-09 00:53
FYI that stacktrace was from same version of source I was using when the bug was filed. I also wanted to try reproducing on top of tree but got stuck -- maybe you forgot to push latest commits in fleece submodule?

```
$ git submodule update
fatal: reference is not a tree: 46d46f877488b95b75994b4150b03ca32a15527e
Unable to checkout '46d46f877488b95b75994b4150b03ca32a15527e' in submodule path 'vendor/fleece'
```

**Comment by borrrden** [comment] 2018-06-09 02:28
This seems closely related to what I am chasing down at the moment ( #522 ).

**Comment by borrrden** [comment] 2018-06-09 02:30
As far as the submodule, the commit at https://github.com/couchbase/couchbase-lite-core/commit/9b5a705cd717a23cf3e27a9da20ea4523690c83a should have SHA 0b320b7, not the one you mentioned.

**Comment by SJLC** [comment] 2018-06-09 08:37
Yes the submodules were fine back in commit 9b5a705 -- by "top of tree" I meant the current master HEAD of c69094e7ba where fleece checkout is now broken

In particular, see recent fleece update as part of 503253
```
diff --git a/vendor/fleece b/vendor/fleece
index cb0c67a..46d46f8 160000
--- a/vendor/fleece
+++ b/vendor/fleece
@@ -1 +1 @@
-Subproject commit cb0c67a0fe0885a9edc5fe01f4efeccf0e9ee3a7
+Subproject commit 46d46f877488b95b75994b4150b03ca32a15527e
```

**Comment by borrrden** [comment] 2018-06-09 12:15
In that case your theory is almost certainly correct.  @snej Can you check on the fleece submodule?

**Comment by snej** [comment] 2018-06-11 00:46
Sorry, I forgot to push changes to Fleece on Friday. Fixed now.

The cause of the crash (the one you logged the backtrace of, on 6/8) is a race condition where one thread releases the last reference to the Replicator, triggering its destructor, while another thread retains the same Replicator. That implies the second thread didn't have a proper reference to it.

Is it possible to repeat that crash? If so, it would be great to see the backtrace of the thread that's logging `RefCounted object at %p retained while it had an invalid refCount of 0`. Could you set a breakpoint at that line and capture the backtrace?

**Comment by SJLC** [comment] 2018-06-15 09:36
On x86-64, no more crashes in 14000 and 32000 iterations of "API Connection Failure" and "API Loopback Push" tests respectively; haven't tried it yet on ARM target.

**Comment by borrrden** [comment] 2018-06-15 22:15
Great to hear!  I had a feeling that these two were linked.  I'm eager to hear the ARM results.

**Comment by SJLC** [comment] 2018-06-20 08:36
Did almost 1500 iterations of "API Connection Failure" when one run hung. It did not segfault like previously, Not sure if this change introduced a rare deadlock, or if it is a different bug...

[cb-connection.output.txt](https://github.com/couchbase/couchbase-lite-core/files/2118490/cb-connection.output.txt)
[cb-connection.dbg.txt](https://github.com/couchbase/couchbase-lite-core/files/2118495/cb-connection.dbg.txt)

**Comment by borrrden** [comment] 2018-06-20 10:47
The additional change is extremely unlikely to introduce any deadlocks.  In fact I don't see any dead locks in the thread traces there anyway.  It looks like just for some reason the status didn't change to "stopped", despite the change (at least internally) showing in the output.  The threads show exactly what I would expect:

4 worker threads for the actor scheduler, one timer thread, and the main thread.

**Comment by SJLC** [comment] 2018-06-20 17:35
I got another failure on ARM, didn't hang so I didn't get to attach gdb but here is test output. I suspect you will say it is a different problem altogether and it is time to close this thread; in that case do you want a new issue, or wait to see if a better way to reproduce it turns up?
[cb-connection.output2.txt](https://github.com/couchbase/couchbase-lite-core/files/2120426/cb-connection.output2.txt)

**Comment by borrrden** [comment] 2018-06-20 21:36
If it is not reproducible then I'd hold off on creating an issue unless it happens quite frequently.  According to the logs the error did not get set, which is an odd thing to not happen deterministically.  Maybe later @snej can look and see if he sees anything, but as for this issue I think it has been resolved.

**Closed** 2018-06-21 23:08 UTC
Labels: ffp
