### ISSUE TITLE
Stopping continuous replication causes assertion failure

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#319] opened 2017-12-15 08:22 UTC
Seen on Linux platform during .NET StopContinuousReplication test:

> /home/couchbase/jenkins/workspace/couchbase-lite-core-linux/couchbase-lite-core/vendor/BLIP-Cpp/include/blip_cpp/MockProvider.hh:35: virtual bool litecore::websocket::MockWebSocket::send(fleece::slice, bool): Assertion `_isOpen' failed.

**Comment by borrrden** [comment] 2017-12-20 07:45
This one is causing a lot of grief lately with the addition of the StopContinuousReplicator test (which quickly stops and starts continuous replicators in succession).  Can we alter the behavior here?  I assume the problem is that there is a race between the send and the close.  If it is found to be closed, could we just log something and move on instead of asserting?

**Comment by borrrden** [comment] 2017-12-23 00:58
Possibly related.  Just crashed on macOS

> Thread 11 Crashed:: Dispatch queue: BLIP[->file:/var/folders/7p/_46f70_11vv_jglsrqcp5kth0000gn/T/CouchbaseLite/otherdb.cblite2/]
0   libdispatch.dylib             	0x00007fff7d5b4da8 _dispatch_continuation_push + 4
1   libLiteCore.dylib             	0x0000000105b3fd4b void litecore::actor::Actor::enqueue<litecore::websocket::MockWebSocket, int, fleece::alloc_slice>(void (litecore::websocket::MockWebSocket::*)(int, fleece::alloc_slice), int, fleece::alloc_slice) + 171
2   libLiteCore.dylib             	0x0000000105b3e4c7 litecore::websocket::MockWebSocket::close(int, fleece::slice) + 135
3   libLiteCore.dylib             	0x0000000105bbea3b litecore::blip::BLIPIO::_close() + 123
4   libLiteCore.dylib             	0x0000000105babf36 invocation function for block in void litecore::actor::Actor::enqueue<litecore::blip::BLIPIO>(void (litecore::blip::BLIPIO::*)()) + 102
5   libLiteCore.dylib             	0x0000000105bc53f6 litecore::actor::safelyCall(void () block_pointer) + 22
6   libLiteCore.dylib             	0x0000000105bc53c4 invocation function for block in litecore::actor::GCDMailbox::enqueue(void () block_pointer) + 36
7   libdispatch.dylib             	0x00007fff7d5a96cd _dispatch_call_block_and_release + 12
8   libdispatch.dylib             	0x00007fff7d5a1e88 _dispatch_client_callout + 8
9   libdispatch.dylib             	0x00007fff7d5b6356 _dispatch_queue_serial_drain + 635
10  libdispatch.dylib             	0x00007fff7d5a9239 _dispatch_queue_invoke + 373
11  libdispatch.dylib             	0x00007fff7d5b7042 _dispatch_root_queue_drain_deferred_wlh + 332
12  libdispatch.dylib             	0x00007fff7d5bae1b _dispatch_workloop_worker_thread + 880
13  libsystem_pthread.dylib       	0x00007fff7d865033 _pthread_wqthread + 980
14  libsystem_pthread.dylib       	0x00007fff7d864c4d start_wqthread + 13

> Thread 17:: Dispatch queue: Pull<-file:/var/folders/7p/_46f70_11vv_jglsrqcp5kth0000gn/T/CouchbaseLite/testdb0.cblite2/
0   libsystem_kernel.dylib        	0x00007fff7d72aeae __psynch_mutexwait + 10
1   libsystem_pthread.dylib       	0x00007fff7d865bfe _pthread_mutex_lock_wait + 83
2   libsystem_pthread.dylib       	0x00007fff7d863551 _pthread_mutex_lock_slow + 253
3   libLiteCore.dylib             	0x0000000105c0e985 pthreadMutexEnter + 21
4   libLiteCore.dylib             	0x0000000105bf2e84 sqlite3_mutex_enter + 36
5   libLiteCore.dylib             	0x0000000105bf0ae5 sqlite3_free + 53
6   libLiteCore.dylib             	0x0000000105c0d6c1 sqlite3DbFreeNN + 145
7   libLiteCore.dylib             	0x0000000105bf3c88 sqlite3DbFree + 40
8   libLiteCore.dylib             	0x0000000105c2aa2f vdbeFreeOpArray + 127
9   libLiteCore.dylib             	0x0000000105bf6e29 sqlite3VdbeClearObject + 249
10  libLiteCore.dylib             	0x0000000105c2ab24 sqlite3VdbeDelete + 52
11  libLiteCore.dylib             	0x0000000105bfdf2a sqlite3VdbeFinalize + 74
12  libLiteCore.dylib             	0x0000000105bfdd7f sqlite3_finalize + 143
13  libLiteCore.dylib             	0x0000000105a6ae7f SQLite::Statement::Ptr::~Ptr() + 207
14  libLiteCore.dylib             	0x0000000105a67f25 SQLite::Statement::Ptr::~Ptr() + 21
15  libLiteCore.dylib             	0x0000000105a68111 SQLite::Statement::~Statement() + 65
16  libLiteCore.dylib             	0x0000000105a68145 SQLite::Statement::~Statement() + 21
17  libLiteCore.dylib             	0x0000000105a68169 SQLite::Statement::~Statement() + 25
18  libLiteCore.dylib             	0x0000000105a1398b litecore::SQLiteKeyStore::close() + 491
19  libLiteCore.dylib             	0x00000001059f1f05 litecore::DataFile::close() + 709
20  libLiteCore.dylib             	0x0000000105a0b29b litecore::SQLiteDataFile::close() + 43
21  libLiteCore.dylib             	0x0000000105a098a3 litecore::SQLiteDataFile::~SQLiteDataFile() + 51
22  libLiteCore.dylib             	0x0000000105a09ef5 litecore::SQLiteDataFile::~SQLiteDataFile() + 21
23  libLiteCore.dylib             	0x0000000105a09f19 litecore::SQLiteDataFile::~SQLiteDataFile() + 25
24  libLiteCore.dylib             	0x0000000105982a77 c4Internal::Database::~Database() + 2775
25  libLiteCore.dylib             	0x0000000105a50dfe c4Database::~c4Database() + 62
26  libLiteCore.dylib             	0x0000000105a50e45 c4Database::~c4Database() + 21
27  libLiteCore.dylib             	0x0000000105a50e69 c4Database::~c4Database() + 25
28  libLiteCore.dylib             	0x0000000105a545fc litecore::RefCounted::_release() + 252
29  libLiteCore.dylib             	0x0000000105a519c0 litecore::release(litecore::RefCounted*) + 32
30  libLiteCore.dylib             	0x0000000105a51981 c4db_free + 65
31  libLiteCore.dylib             	0x0000000105b47205 c4::freeRef(c4Database*) + 21
32  libLiteCore.dylib             	0x0000000105b471ca c4::ref<c4Database>::~ref() + 42
33  libLiteCore.dylib             	0x0000000105b3ca25 c4::ref<c4Database>::~ref() + 21
34  libLiteCore.dylib             	0x0000000105ad3f28 litecore::repl::DBWorker::~DBWorker() + 376
35  libLiteCore.dylib             	0x0000000105ad3175 litecore::repl::DBWorker::~DBWorker() + 21
36  libLiteCore.dylib             	0x0000000105ad3199 litecore::repl::DBWorker::~DBWorker() + 25
37  libLiteCore.dylib             	0x0000000105a545fc litecore::RefCounted::_release() + 252
38  libLiteCore.dylib             	0x0000000105a519c0 litecore::release(litecore::RefCounted*) + 32
39  libLiteCore.dylib             	0x00000001059d5658 litecore::Retained<litecore::DataFile::Shared>::~Retained() + 24
40  libLiteCore.dylib             	0x00000001059d55d5 litecore::Retained<litecore::DataFile::Shared>::~Retained() + 21
41  libLiteCore.dylib             	0x0000000105af1154 litecore::repl::Puller::~Puller() + 116
42  libLiteCore.dylib             	0x0000000105aef245 litecore::repl::Puller::~Puller() + 21
43  libLiteCore.dylib             	0x0000000105aef269 litecore::repl::Puller::~Puller() + 25
44  libLiteCore.dylib             	0x0000000105a545fc litecore::RefCounted::_release() + 252
45  libLiteCore.dylib             	0x0000000105a519c0 litecore::release(litecore::RefCounted*) + 32
46  libLiteCore.dylib             	0x0000000105bc5641 litecore::actor::GCDMailbox::afterEvent() + 241
47  libLiteCore.dylib             	0x0000000105bc53cd invocation function for block in litecore::actor::GCDMailbox::enqueue(void () block_pointer) + 45
48  libdispatch.dylib             	0x00007fff7d5a96cd _dispatch_call_block_and_release + 12
49  libdispatch.dylib             	0x00007fff7d5a1e88 _dispatch_client_callout + 8
50  libdispatch.dylib             	0x00007fff7d5b6356 _dispatch_queue_serial_drain + 635
51  libdispatch.dylib             	0x00007fff7d5a9239 _dispatch_queue_invoke + 373
52  libdispatch.dylib             	0x00007fff7d5b7042 _dispatch_root_queue_drain_deferred_wlh + 332
53  libdispatch.dylib             	0x00007fff7d5bae1b _dispatch_workloop_worker_thread + 880
54  libsystem_pthread.dylib       	0x00007fff7d865033 _pthread_wqthread + 980
55  libsystem_pthread.dylib       	0x00007fff7d864c4d start_wqthread + 13

> Thread 20:
0   libsystem_kernel.dylib        	0x00007fff7d72aeae __psynch_mutexwait + 10
1   libsystem_pthread.dylib       	0x00007fff7d865bfe _pthread_mutex_lock_wait + 83
2   libsystem_pthread.dylib       	0x00007fff7d863551 _pthread_mutex_lock_slow + 253
3   libLiteCore.dylib             	0x0000000105c0e985 pthreadMutexEnter + 21
4   libLiteCore.dylib             	0x0000000105bf2e84 sqlite3_mutex_enter + 36
5   libLiteCore.dylib             	0x0000000105bf436b sqlite3Malloc + 75
6   libLiteCore.dylib             	0x0000000105c4e210 sqlite3HashInsert + 176
7   libLiteCore.dylib             	0x0000000105c5befb sqlite3CreateIndex + 4347
8   libLiteCore.dylib             	0x0000000105c5add4 sqlite3AddPrimaryKey + 740
9   libLiteCore.dylib             	0x0000000105c55456 yy_reduce + 1270
10  libLiteCore.dylib             	0x0000000105c54c62 sqlite3Parser + 146
11  libLiteCore.dylib             	0x0000000105c05902 sqlite3RunParser + 466
12  libLiteCore.dylib             	0x0000000105c5449e sqlite3Prepare + 702
13  libLiteCore.dylib             	0x0000000105c04960 sqlite3LockAndPrepare + 144
14  libLiteCore.dylib             	0x0000000105c048bc sqlite3_prepare + 76
15  libLiteCore.dylib             	0x0000000105c3e6b8 sqlite3InitCallback + 328
16  libLiteCore.dylib             	0x0000000105bf5850 sqlite3_exec + 672
17  libLiteCore.dylib             	0x0000000105cce254 sqlite3InitOne + 1108
18  libLiteCore.dylib             	0x0000000105c0b1fd sqlite3Init + 109
19  libLiteCore.dylib             	0x0000000105c52703 sqlite3ReadSchema + 67
20  libLiteCore.dylib             	0x0000000105c65608 sqlite3Pragma + 968
21  libLiteCore.dylib             	0x0000000105c57e91 yy_reduce + 12081
22  libLiteCore.dylib             	0x0000000105c54c62 sqlite3Parser + 146
23  libLiteCore.dylib             	0x0000000105c05902 sqlite3RunParser + 466
24  libLiteCore.dylib             	0x0000000105c5449e sqlite3Prepare + 702
25  libLiteCore.dylib             	0x0000000105c04960 sqlite3LockAndPrepare + 144
26  libLiteCore.dylib             	0x0000000105bffec9 sqlite3Reprepare + 105
27  libLiteCore.dylib             	0x0000000105bff9f7 sqlite3_step + 199
28  libLiteCore.dylib             	0x0000000105a69458 SQLite::Statement::executeStep() + 72
29  libLiteCore.dylib             	0x0000000105a0d461 litecore::SQLiteDataFile::intQuery(char const*) + 113
30  libLiteCore.dylib             	0x0000000105a0b90c litecore::SQLiteDataFile::optimizeAndVacuum() + 44
31  libLiteCore.dylib             	0x0000000105a0b4be litecore::SQLiteDataFile::close() + 590
32  libLiteCore.dylib             	0x0000000105982b42 c4Internal::Database::close() + 66
33  libLiteCore.dylib             	0x0000000105a56103 void litecore::function_ref<void ()>::callback_fn<std::__1::__bind<void (c4Internal::Database::*)(), c4Database*&> >(long) + 243
34  libLiteCore.dylib             	0x0000000105a5fb59 litecore::function_ref<void ()>::operator()() const + 25
35  libLiteCore.dylib             	0x0000000105a5fabd c4Internal::tryCatch(C4Error*, litecore::function_ref<void ()>) + 29
36  libLiteCore.dylib             	0x0000000105a518db c4db_close + 491

**Comment by snej** [comment] 2018-01-11 19:47
@borrrden, have you seen any more crashes (or related glitches) like this on Linux since you pushed your BLIP changes?

The Mac crash is from BLIPIO calling close on its WebSocket after (apparently) the WebSocket was deleted. I'll look into that.

**Comment by snej** [comment] 2018-01-16 23:54
It's likely this was caused by the same problem as #353, so it should also be fixed by the same commit, 2f965d5280.

**Closed by snej** 2018-01-16 23:54 UTC
Labels: backlog
