### ISSUE TITLE
Corrupt revision data when using index + null value + left join

### ISSUE THREAD

**Issue by gnujeremie** [couchbase/couchbase-lite-core#840] opened 2019-09-10 15:42 UTC
Hi, I'm reporting (I think) a bug impacting couchbase lite on iOS and Android.

I have the following index (and several other, but not relevant here) :

```
database.createIndex("medicalFilesList",
        IndexBuilder.valueIndex(
                ValueIndexItem.property("type"),
                ValueIndexItem.property("mftCategory"),
                ValueIndexItem.property("mefAssignedTo"),
                ValueIndexItem.property("sysActive"),
                ValueIndexItem.property("mefPrescriptionStartDate")
        )
);

```

And the following request : 
```
 Expression whereExpression = Expression.property("type").from("mef").equalTo(Expression.string("pulseMedicalFile"))
    .and(Expression.property("ageId").from("mef").equalTo(Expression.string(ageId)))
    .and(Expression.property("mftCategory").from("mef").in(categories))
    .and(Expression.property("mefSuspended").from("mef").equalTo(Expression.booleanValue(false)))
    .and(Expression.property("sysActive").from("mef").equalTo(Expression.booleanValue(true)));

if (!mefAssignedTo.equals("") && mefAssignedTo != null && !mefAssignedTo.equals("null")) {
    whereExpression = whereExpression.and(Expression.property("mefAssignedTo").from("mef").equalTo(Expression.string(mefAssignedTo)));
}

Query query = QueryBuilder
.select(SelectResult.expression(Expression.property("id").from("mef")),
        SelectResult.expression(Expression.property("type").from("mef")),
        SelectResult.expression(Expression.property("mefQuizMedical").from("mef")),
        SelectResult.expression(Expression.property("mefQuizEquipment").from("mef")),
        SelectResult.expression(Expression.property("sysCredate").from("mef")),
        SelectResult.expression(Expression.property("preRequiredDocuments").from("pre")),
        SelectResult.expression(Expression.property("fullName").from("usr")),
        SelectResult.expression(Expression.property("color").from("usr")))
.from(DataSource.database(database).as("mef"))
.join(Join.leftJoin(DataSource.database(database).as("pre"))
        .on(Meta.id.from("pre").equalTo(Expression.property("mefLastPrescriptionId").from("mef"))),
        Join.leftJoin(DataSource.database(database).as("usr"))
        .on(Meta.id.from("usr").equalTo(Expression.property("mefAssignedTo").from("mef")))
     )
.where(whereExpression)
    .orderBy(Ordering.expression(Expression.property("mefPrescriptionStartDate").from("mef")).descending())
    .limit(Expression.intValue(1000));


```

Then I have several documents matching this request (some typed "pulseMedicalFile", some typed "pulsePrescription" for the first left join and some typed "pulseUser" for the 2nd left join). If I have one of my "pulseMedicalFile" documents with ```mefAssignedTo: null```, then the request fails with the exception ```Corrupt revision data```. If I changed ```mefAssignedTo: null``` to ```mefAssignedTo: ''``` then there is no exception.

If I remove the left joins, the exception disappears.
If I delete the index, it disappears also.

**Comment by snej** [comment] 2019-09-10 20:45
Could you call `explain` on the Query object and paste the result here? That will make it easier for us to reproduce. Thanks.

**Comment by gnujeremie** [comment] 2019-09-11 06:58
Sure, here it is : 

```
SELECT fl_result(fl_value("mef".body, 'id')), fl_result(fl_value("mef".body, 'type')), fl_result(fl_value("mef".body, 'ageId')), fl_result(fl_value("mef".body, 'patId')), fl_result(fl_value("mef".body, 'mftId')), fl_result(fl_value("mef".body, 'mftLabel')), fl_result(fl_value("mef".body, 'mftCategory')), fl_result(fl_value("mef".body, 'mefBarcode')), fl_result(fl_value("mef".body, 'mefReminderDate')), fl_result(fl_value("mef".body, 'mefStatus')), fl_result(fl_value("mef".body, 'mefInternalCode')), fl_result(fl_value("mef".body, 'mefExternalCode')), fl_result(fl_value("mef".body, 'mefAssignedTo')), fl_result(fl_value("mef".body, 'mefRecordingDate')), fl_result(fl_value("mef".body, 'mefPrescriptionStartDate')), fl_result(fl_value("mef".body, 'mefUrgent')), fl_result(fl_value("mef".body, 'mefBilling')), fl_result(fl_value("mef".body, 'mefSuspended')), fl_result(fl_value("mef".body, 'mefCompleted')), fl_result(fl_value("mef".body, 'mefPatient')), fl_result(fl_value("mef".body, 'mefDoctors')), fl_result(fl_value("mef".body, 'mefLastPrescriptionId')), fl_result(fl_value("mef".body, 'mefPrescriptions')), fl_result(fl_value("mef".body, 'mefQuizMedical')), fl_result(fl_value("mef".body, 'mefQuizEquipment')), fl_result(fl_value("mef".body, 'sysCredate')), fl_result(fl_value("pre".body, 'preRequiredDocuments')), fl_result(fl_value("usr".body, 'fullName')), fl_result(fl_value("usr".body, 'color')) FROM kv_default AS "mef" LEFT OUTER JOIN kv_default AS "pre" ON ("pre".key = fl_value("mef".body, 'mefLastPrescriptionId')) AND ("pre".flags & 1 = 0) LEFT OUTER JOIN kv_default AS "usr" ON ("usr".key = fl_value("mef".body, 'mefAssignedTo')) AND ("usr".flags & 1 = 0) WHERE ((((fl_value("mef".body, 'type') = 'pulseMedicalFile' AND fl_value("mef".body, 'ageId') = 'pulseAgency::S00001') AND fl_value("mef".body, 'mftCategory') IN ('respiratory', 'drip', 'stoma')) AND fl_value("mef".body, 'mefSuspended') = fl_bool(0)) AND fl_value("mef".body, 'sysActive') = fl_bool(1)) AND ("mef".flags & 1 = 0) ORDER BY fl_value("mef".body, 'mefPrescriptionStartDate') DESC LIMIT MAX(0, 1000)
    
    11|0|0| SEARCH TABLE kv_default AS mef USING INDEX medicalFilesList (<expr>=? AND <expr>=?)
    45|0|0| SEARCH TABLE kv_default AS pre USING INDEX sqlite_autoindex_kv_default_1 (key=?)
    61|0|0| SEARCH TABLE kv_default AS usr USING INDEX sqlite_autoindex_kv_default_1 (key=?)
    177|0|0| USE TEMP B-TREE FOR ORDER BY
    
    {"FROM":[{"AS":"mef"},{"AS":"pre","ON":["=",[".pre._id"],[".mef.mefLastPrescriptionId"]],"JOIN":"LEFT OUTER"},{"AS":"usr","ON":["=",[".usr._id"],[".mef.mefAssignedTo"]],"JOIN":"LEFT OUTER"}],"WHAT":[[".mef.id"],[".mef.type"],[".mef.ageId"],[".mef.patId"],[".mef.mftId"],[".mef.mftLabel"],[".mef.mftCategory"],[".mef.mefBarcode"],[".mef.mefReminderDate"],[".mef.mefStatus"],[".mef.mefInternalCode"],[".mef.mefExternalCode"],[".mef.mefAssignedTo"],[".mef.mefRecordingDate"],[".mef.mefPrescriptionStartDate"],[".mef.mefUrgent"],[".mef.mefBilling"],[".mef.mefSuspended"],[".mef.mefCompleted"],[".mef.mefPatient"],[".mef.mefDoctors"],[".mef.mefLastPrescriptionId"],[".mef.mefPrescriptions"],[".mef.mefQuizMedical"],[".mef.mefQuizEquipment"],[".mef.sysCredate"],[".pre.preRequiredDocuments"],[".usr.fullName"],[".usr.color"]],"WHERE":["AND",["AND",["AND",["AND",["=",[".mef.type"],"pulseMedicalFile"],["=",[".mef.ageId"],"pulseAgency::S00001"]],["IN",[".mef.mftCategory"],["[]","respiratory","drip","stoma"]]],["=",[".mef.mefSuspended"],false]],["=",[".mef.sysActive"],true]],"ORDER_BY":[["DESC",[".mef.mefPrescriptionStartDate"]]],"LIMIT":1000}

```

**Comment by borrrden** [comment] 2019-09-17 05:29
That's a pretty massive query statement, is there any chance you see this on a smaller one?  Otherwise we have to reverse engineer some data to test this with and that will take some time.

**Comment by gnujeremie** [comment] 2019-09-19 07:08
Sorry, it's the only query where I have this error (I don't have any other queries with left joins on a null indexed value).

**Comment by borrrden** [comment] 2019-09-19 09:10
I missed the section where you give some information about the conditions where it happens.  I think that will be enough to go forward, but it would be even faster if you are able to provide some complete sample documents showing the problem.  Filed [CBL-414](https://issues.couchbase.com/browse/CBL-414)

**Comment by borrrden** [comment] 2019-10-07 21:35
Looks like this might be able to simplify to just selecting the ID when the join is on a key whose value is `null` so that might be a good place to start.

**Comment by Sandychuang8** [comment] 2019-10-07 21:50
I will still need the complete sample and the query to reproduce this issue.

**Comment by borrrden** [comment] 2019-10-07 22:04
@gnujeremie Also if you could inform us if any part of this query can be removed and still cause the issue (e.g. index only on `mefAssignedTo` and using only the left join via `mefAssignedTo` that will be useful as well.)

**Comment by gnujeremie** [comment] 2019-10-08 06:49
Ok I'll try to answer your questions as soon as I can :)

**Comment by borrrden** [comment] 2020-02-07 11:49
This fix is in 2.7.0. Will close if I don't hear back in 7 days.

**Closed** 2020-02-19 22:58 UTC
Labels: bug :bug:, triaged 👩‍⚕️

**Comment by gnujeremie** [comment] 2021-04-21 08:18
Hi there, 

The bug is still there, https://issues.couchbase.com/browse/CBL-414 says it is not resolved, and I just faced the issue on another case.

Still same problem : 
- create an index on several properties
- have one of thoses properties with value `null`
- query with left join on that property.

The index : 
```
                database.createIndex("calendarEventsAdv1",
                    IndexBuilder.valueIndex(
                        ValueIndexItem.property("type"),
                        ValueIndexItem.property("eveStartDate"),
                        ValueIndexItem.property("eveStopDate"),
                        ValueIndexItem.property("eveStatus"),
                        ValueIndexItem.property("eveType"),
                        ValueIndexItem.property("mefId"),
                        ValueIndexItem.property("usrId"),
                        ValueIndexItem.property("eveDuration")
                    )
                );

```

The query  (I tried to simplify it to paste it here) : 

```
            Expression whereExpression = Expression.property("type").from("event").equalTo(Expression.string("pulseCalendarEvent"));

             whereExpression = whereExpression.and(Expression.property("mftCategory").from("_medicalfile").in(categories)
                        .or(Expression.property("mefId").from("event").isNullOrMissing()));

            Query query = QueryBuilder
                .select(SelectResult.expression(Expression.property("id").from("event")),
                    SelectResult.expression(Expression.property("type").from("event")),
                    SelectResult.expression(Expression.property("agdId").from("event")))
                .from(DataSource.database(database).as("event"))
                .join(Join.leftJoin(DataSource.database(database).as("_medicalfile"))
                           .on(Meta.id.from("_medicalfile").equalTo(Expression.property("mefId").from("event"))),
                        Join.leftJoin(DataSource.database(database).as("oauthuser"))
                                .on(Meta.id.from("oauthuser").equalTo(Expression.property("usrId").from("event"))))
                .where(whereExpression)
                .orderBy(Ordering.expression(Expression.property("eveStartDate").from("event")).ascending(),
                        Ordering.expression(Expression.property("eveDuration").from("event")).descending())
                .limit(Expression.intValue(100));
```

One document with the null value : 

```
{
      "agdId": "pulseAgenda::S00001",
      "ageId": "pulseAgency::S00001",
      "eveAddress": {
        "addressActive": true,
        "addressCity": "Paris",
        "addressCountry": null,
        "addressLatitude": null,
        "addressLine1": "Ma rue",
        "addressLine2": null,
        "addressLongitude": null,
        "addressType": "home",
        "addressZipcode": "75000"
      },
      "eveComment": null,
      "eveConfirmed": false,
      "eveConfirmedDate": null,
      "eveDuration": 60,
      "eveLabel": "install",
      "eveNotification": {
        "notificationDate": null,
        "notificationDelay": null,
        "notificationUnit": "minutes"
      },
      "eveParticipants": [
        {
          "usrColor": "#ff8f00",
          "usrFullName": "Jérémie",
          "usrId": "OAuthUser::gi3af3cbaef709f1e11e99f9a9f5af5cf496e"
        }
      ],
      "evePhone": null,
      "evePlace": "home",
      "evePrivate": false,
      "eveQuizTreatment": [],
      "eveSchedule": {
        "periodicityEndDate": null,
        "periodicityEndOccurence": null,
        "periodicityEndType": null,
        "periodicityFrequency": null,
        "periodicityMonthDate": null,
        "periodicityMonthDay": null,
        "periodicityMonthDayNumber": null,
        "periodicityMonthIsDate": null,
        "periodicityType": null,
        "periodicityWeekDays": null
      },
      "eveSource": "desktop",
      "eveStartDate": "2021-04-22T05:00:00Z",
      "eveStatus": "planed",
      "eveStopDate": "2021-04-22T06:00:00Z",
      "eveTitle": "adad",
      "eveType": "intervention",
      "eveUrgent": false,
      "eveWarehouseShipping": [],
      "id": "pulseCalendarEvent::5drt0747132d0a26e11eba699f7563f9c1dc2",
      "mefId": null,
      "preId": null,
      "sysActive": true,
      "sysCredate": "2021-04-21T06:54:44Z",
      "sysCrelog": "OAuthUser::gi3af3cbaef709f1e11e99f9a9f5af5cf496e",
      "sysSyncActive": true,
      "sysSyncChannel": [
        "hsem1"
      ],
      "type": "pulseCalendarEvent",
      "usrId": "OAuthUser::gi3af3cbaef709f1e11e99f9a9f5af5cf496e"
    }
```

Side question : we are using the enterprise version of couchbase & CBL. For this issue, I started here on github, but do I have to open the same issue on the entreprise support website to be sure this issue will be looked at ?

Thanks a lot, let me know if you need more informations.

**Comment by borrrden** [comment] 2021-04-23 02:42
For enterprise, you should work with your support contract and that will bump the priority.  No need to also file it here.  GH issues and support reported issues are both just an avenue to potentially get an issue into our JIRA, where the issue will actually be tracked and scheduled.  For this issue I can't actually remember why this was closed since, as you noted, the true ticket is still open.  It may have been as simple as an accidental closure while bulk closing GH issues during a release.  With the sample document now things should be able to go forward.

**Comment by borrrden** [comment] 2021-04-23 02:44
Also, as before, the explain output would be appreciated!
