### ISSUE TITLE
BLIP Error during replication causes application abort

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#298] opened 2017-11-09 23:12 UTC
E.g. the recent change to throw a runtime error when an invalid request is received.

After that, the connection closes but further messages (such as close, or set checkpoint) will cause an abort due to the mailbox being `null`

![readaccessviolation](https://user-images.githubusercontent.com/2470288/32634376-b5e96f1c-c5ee-11e7-9242-1370cebc8156.png)

Location of the actual crash
![crashlocation](https://user-images.githubusercontent.com/2470288/32634393-c3c1a370-c5ee-11e7-9565-c500c189afd7.png)

Point at which the null object was entered
![nullobject](https://user-images.githubusercontent.com/2470288/32634402-cd5d7454-c5ee-11e7-910a-1f41732be4bb.png)

**Comment by borrrden** [comment] 2017-11-09 23:15
Another place that this happens is inside enqueueAfter where the mailbox is null:

`std::lock_guard<mutex> lock(_mutex);` <-- Invalid mutex

**Comment by snej** [comment] 2017-11-10 22:41
The crash in saveCheckpoint looks like a race condition where the save was triggered right before the connection closed, so `Replicator::_saveCheckpoint` got invoked anyway. I've added a test at the start of that method to skip the save if the connection is closed.
I found some other intermittent errors when the BLIP connection disconnects, and fixed those too.

**Comment by snej** [comment] 2017-11-11 00:15
Hm, I was about to ask @borrrden to try to reproduce this on Windows, but the previous replicator fixes mean the exception's not going to happen anymore (hopefully). I think I'll just close the issue.

**Comment by borrrden** [comment] 2017-11-11 00:16
I could force it to happen by making BLIP throw an exception on a normal message ;)

**Closed by snej** 2017-11-11 00:15 UTC
Labels: bug, f/replicator, in progress, P1: high, ready

**Comment by borrrden** [comment] 2017-11-11 00:23
Confirmed crash no longer happens, but happens on the commit before this one.

**Comment by snej** [comment] 2017-11-11 01:26
>I could force it to happen by making BLIP throw an exception on a normal message ;)

I did that too, to debug & fix the issue. Kept running it over and over to flush out various errors and crashes.
