### ISSUE TITLE
FTS with alias exception

### ISSUE THREAD

**Issue by gnujeremie** [couchbase/couchbase-lite-core#842] opened 2019-09-11 14:52 UTC
Hi,

I'm trying to write a query using FTS and a FTS index, and it seems to fail in combination with left joins and table alias : 

Here's the fts index definition : 
```
// Index FTS
if (!indices.contains("ftsPatientFullName")) {
      database.createIndex("ftsPatientFullName",
              IndexBuilder.fullTextIndex(
                  FullTextIndexItem.property("mefPatient.mefPatientLastName"),
                  FullTextIndexItem.property("mefPatient.mefPatientFirstName")
                  )
              );
}
```

My request looks like this : 

```
Expression whereExpression = Expression.property("type").from("mef").equalTo(Expression.string("pulseMedicalFile"))
        .and(Expression.property("ageId").from("mef").equalTo(Expression.string(ageId)))
        .and(Expression.property("mftCategory").from("mef").in(categories))
        .and(Expression.property("mefSuspended").from("mef").equalTo(Expression.booleanValue(false)))
        .and(Expression.property("sysActive").from("mef").equalTo(Expression.booleanValue(true)));

// Limité à un utilisateur ?
if (!mefAssignedTo.equals("") && mefAssignedTo != null && !mefAssignedTo.equals("null")) {
    whereExpression = whereExpression.and(
            Expression.property("mefAssignedTo").from("mef").equalTo(Expression.string(mefAssignedTo))
            .or(Expression.property("sysCrelog").from("mef").equalTo(Expression.string(mefAssignedTo))
               )
            );
}

Ordering[] orderings = new Ordering[] {};

// Limité aux rappels ?
if (!mefReminderDate.equals("null")) {
    whereExpression = whereExpression.and(Expression.property("mefReminderDate").from("mef").lessThanOrEqualTo(Expression.string(mefReminderDate)));

    // Tri sur la date de rappel
    orderings = new Ordering[1];
    orderings[0] = Ordering.expression(Expression.property("mefReminderDate").from("mef")).descending();
} else {
    // Tri sur le statut et la date de prescription
    orderings = new Ordering[2];
    orderings[0] = Ordering.expression(Expression.property("mefStatus").from("mef")).descending();
    orderings[1] = Ordering.expression(Expression.property("mefPrescriptionStartDate").from("mef")).descending();
}

// Recherche : Si number, on cherche dans le mefInternalCode, sinon dans le nom et prénom du patient
if (!search.equals("null")) {
    if (NumberUtils.isNumeric(search)) {
        whereExpression = whereExpression.and(Expression.property("mefInternalCode").from("mef").like(Expression.string(search + "%")));
    } else {


        //  FTS INDEX USED HERE 
        Expression patientFTSExpression = FullTextExpression.index("ftsPatientFullName").match(search) ;
        whereExpression = whereExpression.and(patientFTSExpression);
    }



}

Query query = QueryBuilder
        .select(SelectResult.expression(Expression.property("id").from("mef")),
                SelectResult.expression(Expression.property("type").from("mef")),
                SelectResult.expression(Expression.property("ageId").from("mef")),
                SelectResult.expression(Expression.property("patId").from("mef")),
                SelectResult.expression(Expression.property("mftId").from("mef")),
                SelectResult.expression(Expression.property("mftLabel").from("mef")),
                SelectResult.expression(Expression.property("mftCategory").from("mef")),
                SelectResult.expression(Expression.property("mefBarcode").from("mef")),
                SelectResult.expression(Expression.property("mefReminderDate").from("mef")),
                SelectResult.expression(Expression.property("mefStatus").from("mef")),
                SelectResult.expression(Expression.property("mefInternalCode").from("mef")),
                SelectResult.expression(Expression.property("mefExternalCode").from("mef")),
                SelectResult.expression(Expression.property("mefAssignedTo").from("mef")),
                SelectResult.expression(Expression.property("mefRecordingDate").from("mef")),
                SelectResult.expression(Expression.property("mefPrescriptionStartDate").from("mef")),
                SelectResult.expression(Expression.property("mefUrgent").from("mef")),
                SelectResult.expression(Expression.property("mefBilling").from("mef")),
                SelectResult.expression(Expression.property("mefSuspended").from("mef")),
                SelectResult.expression(Expression.property("mefCompleted").from("mef")),
                SelectResult.expression(Expression.property("mefPatient").from("mef")),
                SelectResult.expression(Expression.property("mefDoctors").from("mef")),
                SelectResult.expression(Expression.property("mefLastPrescriptionId").from("mef")),
                SelectResult.expression(Expression.property("mefPrescriptions").from("mef")),
                SelectResult.expression(Expression.property("mefQuizMedical").from("mef")),
                SelectResult.expression(Expression.property("mefQuizEquipment").from("mef")),
                SelectResult.expression(Expression.property("sysCredate").from("mef")),
                SelectResult.expression(Expression.property("preRequiredDocuments").from("pre")),
                SelectResult.expression(Expression.property("fullName").from("usr")),
                SelectResult.expression(Expression.property("color").from("usr")))
        .from(DataSource.database(database).as("mef"))
        .join(Join.leftJoin(DataSource.database(database).as("pre"))
                        .on(Meta.id.from("pre").equalTo(Expression.property("mefLastPrescriptionId").from("mef"))),
              Join.leftJoin(DataSource.database(database).as("usr"))
                        .on(Meta.id.from("usr").equalTo(Expression.property("mefAssignedTo").from("mef")))
        )
        .where(whereExpression)
        .orderBy(orderings)
        .limit(Expression.intValue(50));
```

And I get the following exception : 

```
09-11 16:41:01.149 W/CouchbaseLite/DATABASE: {DB#1} SQLite error compiling statement "SELECT "mef".mef.rowid, offsets(fts1."kv_default::ftsPatientFullName"), fl_result(fl_value("mef".body, 'id')), fl_result(fl_value("mef".body, 'type')), fl_result(fl_value("mef".body, 'ageId')), fl_result(fl_value("mef".body, 'patId')), fl_result(fl_value("mef".body, 'mftId')), fl_result(fl_value("mef".body, 'mftLabel')), fl_result(fl_value("mef".body, 'mftCategory')), fl_result(fl_value("mef".body, 'mefBarcode')), fl_result(fl_value("mef".body, 'mefReminderDate')), fl_result(fl_value("mef".body, 'mefStatus')), fl_result(fl_value("mef".body, 'mefInternalCode')), fl_result(fl_value("mef".body, 'mefExternalCode')), fl_result(fl_value("mef".body, 'mefAssignedTo')), fl_result(fl_value("mef".body, 'mefRecordingDate')), fl_result(fl_value("mef".body, 'mefPrescriptionStartDate')), fl_result(fl_value("mef".body, 'mefUrgent')), fl_result(fl_value("mef".body, 'mefBilling')), fl_result(fl_value("mef".body, 'mefSuspended')), fl_result(fl_value("mef".body, 'mefCompleted')), fl_result(fl_value("mef".body, 'mefPatient')), fl_result(fl_value("mef".body, 'mefDoctors')), fl_result(fl_value("mef".body, 'mefLastPrescriptionId')), fl_result(fl_value("mef".body, 'mefPrescriptions')), fl_result(fl_value("mef".body, 'mefQuizMedical')), fl_result(fl_value("mef".body, 'mefQuizEquipment')), fl_result(fl_value("mef".body, 'sysCredate')), fl_result(fl_value("pre".body, 'preRequiredDocuments')), fl_result(fl_value("usr".body, 'fullName')), fl_result(fl_value("usr".body, 'color')) FROM kv_default AS "mef" LEFT OUTER JOIN kv_default AS "pre" ON ("pre".key = fl_value("mef".body, 'mefLastPrescriptionId')) AND ("pre".flags & 1 = 0) LEFT OUTER JOIN kv_default AS "usr" ON ("usr".key = fl_value("mef".body, 'mefAssignedTo')) AND ("usr".flags & 1 = 0) JOIN "kv_default::ftsPatientFullName" AS fts1 ON fts1.docid = "mef".rowid WHERE (fts1."kv_default::ftsPatientFullName" MATCH 'Bur*' AND ((((((fl_value("mef".body, 'type') = 'pulseMedicalFile' AND fl_value("mef".body, 'ageId') = 'pulseAgency::S00001') AND fl_value("
09-11 16:41:01.150 E/Pulse: no such column: mef.mef.rowid
```

Removing only the left joins and keeping the alias fails, but removing the aliases (and the left joins) works.

**Comment by jayahariv** [comment] 2019-09-11 16:28
this is the duplicate of https://github.com/couchbase/couchbase-lite-ios/issues/2540


which is fixed in this commit https://github.com/couchbase/couchbase-lite-core/commit/b7a94380bdd5ade8d6efa74fadfacb6e586cfd56

**Comment by gnujeremie** [comment] 2019-09-11 17:35
Awesome, thxs

Le 11 septembre 2019 18:28:58 GMT+02:00, Jayahari Vavachan <notifications@github.com> a écrit :
>this is the duplicate of
>https://github.com/couchbase/couchbase-lite-ios/issues/2540
>
>
>which is fixed in this commit
>https://github.com/couchbase/couchbase-lite-core/commit/b7a94380bdd5ade8d6efa74fadfacb6e586cfd56
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/couchbase/couchbase-lite-core/issues/842#issuecomment-530459115

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Closed** 2019-09-11 17:55 UTC
