### ISSUE TITLE
simple query with dollar sign "$" in property name not working

### ISSUE THREAD

**Issue by bpolanec** [couchbase/couchbase-lite-core#767] opened 2019-04-26 06:36 UTC
Hi, 

we have situation that in some of our property names start with dollar sign in documents. 

Using : com.couchbase.lite:couchbase-lite-android:2.1.2 getting exception in query.

In database I have a document which converted toMap() contains "$type" -> "configurationSet".

Executing query:
`QueryBuilder.select(SelectResult.all()).from(DataSource.database(db).where(Expression.property("$type").equalTo(Expression.string("configurationSet"))).execute().allResults();`

will throw exception:
`fl_value: exception! `

if I try to escape the character $ as : `\\$type` query returns 0 results.

Is there a way to query on properties which start with $ sign and get results?

In previous versions of couch this 1.X this was supported we would like to avoid databases data migrations due to such restriction.

**Comment by borrrden** [comment] 2019-04-26 07:47
Seems like a duplicate of https://github.com/couchbase/couchbase-lite-core/issues/623

**Comment by bpolanec** [comment] 2019-04-26 12:13
thanks, seems this is not released yet. No milestone set, any plan for milestone?

**Comment by borrrden** [comment] 2019-04-26 13:11
Correct the fix will be in the next release which is right around the corner (within a week or two).  It was a slip up that it ended up without a milestone.  There are developer preview releases out for it as well which should include the fix.

**Comment by snej** [comment] 2019-05-01 18:14
2.5 is now released.

**Closed by snej** 2019-05-01 18:14 UTC
