### ISSUE TITLE
Unable set to cookie with host and path

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#475] opened 2018-03-19 18:02 UTC
From https://github.com/couchbase/couchbase-lite-ios/issues/2106, the user is using lite core to set the cookie but it seems like the current API to set cookie is taking only host name into account. Should the `c4db_setCookie` also take path into account?

**Comment by snej** [comment] 2018-03-19 23:44
Looks like the problem is that `c4db_getCookie` isn't given the database name, so it doesn't have the full HTTP path and can't match the cookie.

**Comment by snej** [comment] 2018-03-19 23:53
@pasin Does this reflect actual problems with SG authentication in Couchbase Lite? If this is purely an issue using the LiteCore C API, it shouldn't be a P1 since we don't support that API.

**Comment by pasin** [comment] 2018-03-19 23:54
I don't think so.

**Comment by weis** [comment] 2018-03-20 08:41
Hi, is it ok  when I add the path in c4Socket.cc at line 56 to call the constructor for websocket::Address including path definition (this would solve my problem)  ?
``` websocket::Address addressFrom(const C4Address &addr) {
        return websocket::Address(asstring(addr.scheme),
                                  asstring(addr.hostname),
                                  addr.port,
		                  asstring(addr.path) );
 }
```

**Comment by snej** [comment] 2018-03-20 16:40
Yes, that looks like a bug. Now I'm wondering why it doesn't affect Couchbase Lite. Does SG normally not send session cookies with a `path` parameter? (Attn @adamcfraser)

**Comment by bbrks** [comment] 2018-03-20 16:57
@snej It looks like SG sets the `path` param with the database name:

https://github.com/couchbase/sync_gateway/issues/1345
https://github.com/couchbase/sync_gateway/pull/1355

**Comment by snej** [comment] 2018-03-20 17:18
Then I'm confused ... it seems like authenticated replication with SG shouldn't be working, since the cookie won't be used by the replicator due to this bug.

**Comment by pasin** [comment] 2018-03-20 17:27
We have functional tests that test session authenticator. I once tested it manually when looking at an issue about session authenticator in swift before. However I'm not sure if we have tested the case the SG auto renews the session or not. @sridevi-15 can confirm about this.

**Comment by sridevi-15** [comment] 2018-03-20 17:50
we have functional tests for session authenticator and basic authenticator. It worked fine . We had a bug with session authenticator when iOS had code change from obj C to Swift which got fixed on during DB 23 release. 
Also, we have a functional test which sets cookie in the header which works fine

**Comment by snej** [comment] 2018-03-20 18:08
A related issue I just noticed, which doesn't affect SG cookies: couchbase/couchbase-lite-core#480 "Set-Cookie without path doesn’t implicitly use request’s path"

**Closed** 2018-03-20 20:10 UTC
Labels: P2: medium, backlog
