### ISSUE TITLE
dbObserverCallback is firing before the purgeExpiredDocs transaction is ended

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#637] opened 2018-12-18 00:15 UTC
`dbObserverCallback` is getting called before the `purgeExpiredDocs` transaction is ended. And the document expiry is not invoking the `db.changeEventListener`

[reference](https://github.com/couchbase/couchbase-lite-ios/issues/2266)

**Comment by snej** [comment] 2018-12-18 18:05
This is as designed -- the callback is invoked immediately if the DB change is made by the same connection, since the change is immediately visible to that connection. (Other connections' callbacks won't be called until the transaction is committed, since they can't see the changes until commit anyway.)

It sounds like this problem needs to be fixed on the Couchbase Lite side.

**Closed by snej** 2018-12-18 18:05 UTC
